title: Lite SAML
url: "https://litesaml.github.io/"

# Build settings
markdown: kramdown
theme: just-the-docs

# Theme setting
heading_anchors: true

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
