title: Lite SAML
url: "https://litesaml.github.io"

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs

# Theme setting
heading_anchors: true

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
